[build]
  command = "pip install -r requirements.txt"
  publish = "."

[functions]
  # This tells Netlify exactly which folders to zip up for the Python function
  directory = "netlify/functions"
  included_files = ["templates/**", "static/**", "app/**", "*.py"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true # Ensures traffic goes to your function instead of a 404 page