[build]
  command = "pip install -r requirements.txt"
  publish = "."
  [build.environment]
    PYTHON_VERSION = "3.8"

[functions]
  directory = "netlify/functions"
  included_files = ["templates/**", "static/**", "app/**", "*.py"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/handler"
  status = 200
  force = true